### ISSUE TITLE
empty output '??:?'

### ISSUE THREAD

**Issue by pannous** [gimli-rs/addr2line#235] opened 2021-09-20 17:14 UTC
addr2line does not give the desired output, even though file and address were double checked:
```

dli_fname = {const char * | 0x16d576a30} "/Users/me/dev/apps/wasp/cmake-build-default/wasp"
dli_fbase = {void * | 0x102888000} 0x0000000102888000
dli_sname = {const char * | 0x10299e5cf} "_ZN3MapI6String4ListIS0_EEixES0_"
dli_saddr = {void * | 0x1028da510} 0x00000001028da510

Map<String, List<String> >::operator[](String) + 260 @ 0x1028da510 

addr2line -C -f -i --exe wasp 0x0000000102888000
_home
??:?

addr2line -C -f -i --exe wasp 0x00000001028da510
_home
??:?

_home seems to point to something very different
const char *home;

maybe the osx file format is not supported?

hexdump wasp 
00000000  cf fa ed fe 0c …
```

Does some base offset need to be added?

Even though this might be out of scope for this git, any help is appreciated!

**Comment by philipc** [comment] 2021-09-20 21:25
Mach-O files are supported, but addr2line doesn't know how to locate the dsym. You need to specify it instead of the executable.

**Comment by philipc** [comment] 2024-04-12 07:22
Duplicate of #5 and not planning to implement.

**Closed by philipc** 2024-04-12 07:22 UTC
