### ISSUE TITLE
There exist DWARF files in the wild where a program entry's ranges are not contained within the CU

### ISSUE THREAD

**Issue by khuey** [gimli-rs/addr2line#30] opened 2017-02-15 21:26 UTC
Using the separate debug info for libpthread.so.0 on Xenial.

>~/dev/addr2line/target/debug/addr2line -f -e /usr/lib/debug/.build-id/4d/7f52f335dc9665c2dcf308ce6514a6ae86dede.debug 5555
>
>thread 'main' panicked at 'assertion failed: unit.ranges.iter().any(|range| range.begin <= r.begin && range.end >= r.end)', src/lib.rs:597

The DWARF contains an inline subprogram that is not within the CU's declared ranges.

**Comment by fitzgen** [comment] 2017-02-15 21:32
Nice find

**Comment by jonhoo** [comment] 2017-02-15 23:26
That check *should* only be present in debug builds. In a release build, it wouldn't panic, but the inlined subprogram would not be found when resolving.

**Comment by philipc** [comment] 2017-02-16 06:07
debug asserts should still only check for things that should be logically impossible. The only reason they aren't also checked in release builds is for performance (and the documentation for `debug_assert` states that it should only be used instead of `assert` if the performance difference is measurable).

**Comment by jonhoo** [comment] 2017-02-16 15:56
From our earlier discussions about this when it was originally introduced, I would argue that this should never happen, and therefore a debug assert is (or rather, was) reasonable. Now that we've seen a real-world binary with this invariant broken, I agree, that should change. One option is to just remove the assert, and leave the code as is otherwise. Having a subprogram that is not within the CU's declared ranges seems like a bug to me, and it is somewhat reasonable to simply ignore such subprograms. The other option would be more drastic — to fix this we'd need to rewrite the code quite a bit, since it currently *assumes* that this invariant holds in order to do the search efficiently.

I wonder what the other symbol-finding tools do for this particular subprogram. @khuey can you try doing a lookup for an address in the range in question using `addr2line` from `binutils` (or some other place), and compare it to the name resolved by our `addr2line` when compiled in release mode?

**Comment by khuey** [comment] 2017-02-16 17:54
>khuey@minbar:/home/khuey/dev/addr2line$ ./target/release/addr2line -f -e /usr/lib/debug/.build-id/4d/7f52f335dc9665c2dcf308ce6514a6ae86dede.debug 226
>??
>??:?
>khuey@minbar:/home/khuey/dev/addr2line$ addr2line -f -e /usr/lib/debug/.build-id/4d/7f52f335dc9665c2dcf308ce6514a6ae86dede.debug 226??
>??:0

**Comment by jonhoo** [comment] 2017-02-16 17:58
Interesting.. So we actually end up resolving the same as the standard tools. Sounds like they also just ignore this kind of inconsistency then..

**Comment by jonhoo** [comment] 2017-02-26 17:11
I've been thinking some more about this, and keep coming back to the fact that this *seems* like a valid assumption to make. I agree, the program shouldn't crash when the invariant doesn't hold, but failing to resolve those subprograms (like existing tools also do) seems fine. Thoughts?

**Comment by fitzgen** [comment] 2017-02-26 17:19
A couple thoughts:

* In general, we should strive for correctness, and if we can be even more correct than the alternatives, then that's great

* The asserts were asserting against something we believed should never happen. Its been shown that it can happen, so it doesn't make sense to assert against and crash anymore. Initially we should detect and ignore this case, with the hopes that we can eventually detect and correctly handle it.

**Comment by fitzgen** [comment] 2017-02-26 17:22
That is, I think everyone is in agreement about removing the assertions and gracefully failing to resolve the address.

It would be great to also figure out a way to resolve them without losing our sorting and fast past in the future.

**Comment by khuey** [comment] 2017-02-26 17:26
It would be simple enough to expand the ranges the CU covers to include ranges of subprograms that are not within the declared bounds of the CU when parsing.

The more interesting question to me is whether or not the undeclared ranges are actually unique to a single CU.

**Comment by jonhoo** [comment] 2017-02-26 20:59
@khuey yes and no -- we could do that, though we still have #29, and I'm guessing these subprograms will also not be nicely in order with the surrounding line number programs. Also, it might slow down searches significantly, since CUs could now become much wider, meaning more of them have to be searched for any given address.

@fitzgen I'll submit a PR shortly removing the assert in debug mode.

**Comment by jonhoo** [comment] 2017-02-26 21:33
I wonder if the way to resolve this eventually is to move from our sorted vector binary search algorithm to a full [interval tree](https://en.wikipedia.org/wiki/Interval_tree). It'll require more memory, and be somewhat slower to search, but it will have fewer order and hierarchy requirements than the current approach, which would let us deal with both this in #29 in a nicer way...

**Comment by philipc** [comment] 2017-02-27 03:01
It appears that the real problem is gimli isn't parsing the ranges correctly. The ranges we are parsing don't match the `DW_AT_entry_pc` of the inlined subroutine that the ranges are for. Note that libdwarf's dwarfdump can't parse it correctly either, but readelf does:

````
dwarfdump -N /usr/lib/debug/.build-id/4d/7f52f335dc9665c2dcf308ce6514a6ae86dede.debug
                ranges: 4 at .debug_ranges offset 912 (0x00000390) (64 bytes)
                        [ 0] range entry    0x0000021a 0x00000227
                        [ 1] range entry    0x0000022e 0x0000023d
                        [ 2] range entry    0x00000244 0x00000260
                        [ 3] range end      0x00000000 0x00000000

readelf -wR /usr/lib/debug/.build-id/4d/7f52f335dc9665c2dcf308ce6514a6ae86dede.debug
    00000390 00000000000062fa 0000000000006307 
    00000390 000000000000630e 000000000000631d 
    00000390 0000000000006324 0000000000006340 
    00000390 <End of list>
````

I'm not sure yet exactly what the bug is, but I suspect it is related to relocations. eg elfutils relocates addresses in ranges:
````
  bool begin_relocated = READ_AND_RELOCATE (__libdw_relocate_address, begin);
  bool end_relocated = READ_AND_RELOCATE (__libdw_relocate_address, end);
````

and gdb appears to do something too:
````
	  lowpc = gdbarch_adjust_dwarf2_addr (gdbarch,
					      range_beginning + baseaddr);
	  highpc = gdbarch_adjust_dwarf2_addr (gdbarch,
					       range_end + baseaddr);
````

**Comment by jonhoo** [comment] 2017-02-27 03:08
Oh, nice find @philipc! Maybe we can leave the assertions in after all!

**Comment by fitzgen** [comment] 2017-02-27 15:04
> but I suspect it is related to relocations.

Relocations should only matter for shared libs, static libs, and object files that haven't been linked, right? It should *not* affect an executable, correct? What kind of file are you testing on?

But yeah, relocations is something we need to handle eventually, but also something I am not excited about :-/

**Comment by philipc** [comment] 2017-02-28 01:09
> Relocations should only matter for shared libs, static libs, and object files that haven't been linked, right? It should not affect an executable, correct?

Yes you're right. The problem isn't with relocations.

> What kind of file are you testing on?

It's a separate debug file for the libpthread.so.0 dynamic library.

The problem is that range lists are relative to the base address of the compilation unit, as specified by the `DW_AT_low_pc` attribute. However, the compilation unit in question only has a `DW_AT_entry_pc` attribute. From a comment in gdb:

````
/* Find the base address of the compilation unit for range lists and
   location lists.  It will normally be specified by DW_AT_low_pc.
   In DWARF-3 draft 4, the base address could be overridden by
   DW_AT_entry_pc.  It's been removed, but GCC still uses this for
   compilation units with discontinuous ranges.  */
````

**Comment by philipc** [comment] 2017-02-28 01:27
Sorry, that stuff about `DW_AT_entry_pc` isn't the problem (although we probably should fix that too).

The problem is we're looking for `DW_AT_low_pc` in the `DW_TAG_inlined_subroutine` instead of the `DW_TAG_compile_unit`.

**Closed** 2017-02-28 03:10 UTC

**Comment by jonhoo** [comment] 2017-02-28 03:28
@fitzgen @philipc should we put the debug asserts back in now that that was merged? We're fairly confident that this *shouldn't* happen, right?

**Comment by philipc** [comment] 2017-02-28 04:00
I think it would be good to have some way of noticing if this happens again due to some other bug. However, I'm reluctant to add asserts for things that could in fact occur as a result of bad input data (as opposed to misuse of the API). I prefer asserts for things that are pure logic bugs.

We could return a parsing error, but some users may want to ignore this type of error and just get a best effort result. So that's heading down the path of needing a 'strict' configuration option to determine whether to return an error, but that may be overkill.

So my opinion is there isn't a clear best way to handle this, so do whatever you prefer :)

**Comment by jonhoo** [comment] 2017-02-28 05:40
Hmm, yeah, it's not clear to me what the right approach is either.  I lean towards returning an error to the user, as it isn't even clear we'd give useful results for a file with incorrect ranges. Best effort might just be incorrect, and without any indication of that being the case. Alternatively, I also thing having asserts for this only in debug builds might get us pretty far. I'm *guessing* that people who truly care about best effort would be using the release build, whereas a bunch of more casual users will just `cargo run` or otherwise use a debug build, and in those cases we'd like to get reports when our assumptions are violated on a real-world binary...

**Comment by khuey** [comment] 2017-02-28 20:36
Nice catch.
